---
-
  hosts: centos
  user: root

  tasks:
    - name: Configure a MOTD (message of the day)
      copy:
        src: centos_motd
        dest: /etc/motd
        mode: preserve # This will preserve the existing file permission
...
